In [16]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)
from numpy import linalg as LA

In [7]:
A = np.array([[1, 2,0],
              [0, 0,5],
              [3,-4,2],
             [1,6,5],
             [0,1,0]])
print(f'Матрица A:\n{A}')

Матрица A:
[[ 1  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]]


In [10]:
U, s, W = np.linalg.svd(A)
V = W.T
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s
print(f'Матрица D:\n{D}')

Матрица D:
[[8.82 0.   0.  ]
 [0.   6.14 0.  ]
 [0.   0.   2.53]
 [0.   0.   0.  ]
 [0.   0.   0.  ]]


In [11]:
print(f'Матрица U:\n{U}')

Матрица U:
[[ 0.17  0.16 -0.53 -0.8  -0.16]
 [ 0.39 -0.53  0.61 -0.43  0.03]
 [-0.14 -0.82 -0.52  0.14  0.07]
 [ 0.89  0.06 -0.25  0.38 -0.06]
 [ 0.08  0.11 -0.08 -0.11  0.98]]


In [15]:
#евклидова норма матрицы равна евклидовой норме диагональной матрицы из ее сингулярных чисел  D
Ae=np.sqrt(np.sum(s**2))
Ae

11.045361017187265

In [19]:
LA.norm(A)

11.045361017187261

In [20]:
#  норма Фробениуса
LA.norm(A,ord=2)

8.824868854820442